# Generated by Django 4.2.11 on 2026-05-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
    ]
