# Generated by Django 4.2.11 on 2026-05-01 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_auto_20260502_0003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='wallet',
            new_name='account',
        ),
    ]
